/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicImgRouteImport } from './routes/api/public/img'
import { Route as ApiPublicPlayerPhotoIdRouteImport } from './routes/api/public/player-photo.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicImgRoute = ApiPublicImgRouteImport.update({
  id: '/api/public/img',
  path: '/api/public/img',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPlayerPhotoIdRoute = ApiPublicPlayerPhotoIdRouteImport.update({
  id: '/api/public/player-photo/$id',
  path: '/api/public/player-photo/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/img': typeof ApiPublicImgRoute
  '/api/public/player-photo/$id': typeof ApiPublicPlayerPhotoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/img': typeof ApiPublicImgRoute
  '/api/public/player-photo/$id': typeof ApiPublicPlayerPhotoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/img': typeof ApiPublicImgRoute
  '/api/public/player-photo/$id': typeof ApiPublicPlayerPhotoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/public/img' | '/api/public/player-photo/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/public/img' | '/api/public/player-photo/$id'
  id: '__root__' | '/' | '/api/public/img' | '/api/public/player-photo/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicImgRoute: typeof ApiPublicImgRoute
  ApiPublicPlayerPhotoIdRoute: typeof ApiPublicPlayerPhotoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/img': {
      id: '/api/public/img'
      path: '/api/public/img'
      fullPath: '/api/public/img'
      preLoaderRoute: typeof ApiPublicImgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/player-photo/$id': {
      id: '/api/public/player-photo/$id'
      path: '/api/public/player-photo/$id'
      fullPath: '/api/public/player-photo/$id'
      preLoaderRoute: typeof ApiPublicPlayerPhotoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicImgRoute: ApiPublicImgRoute,
  ApiPublicPlayerPhotoIdRoute: ApiPublicPlayerPhotoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
